core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('restaurant_app.urls')),
]

restaurant_app/urls.py
from django.urls import path
from .views import (DishListing, add_item, remove_item, cart_listing, add_item_cart,
                    remove_item_cart, place_order, OrderHistory, order_history, analytics)

app_name = 'restaurant_app'

urlpatterns = [
    path('home/', DishListing.as_view(), name='dish_listing'),

    path('add-item/<int:page>/<str:dish_id>/<str:dish_name>/', add_item, name='add_item'),
    path('add-item/<int:page>/<str:dish_id>/<str:dish_name>/<str:search_term>', add_item, name='add_item'),

    path('remove-item/<int:page>/<str:dish_id>/<str:dish_name>/', remove_item, name='remove_item'),
    path('remove-item/<int:page>/<str:dish_id>/<str:dish_name>/<str:search_term>', remove_item, name='remove_item'),

    path('add-item-cart/<str:dish_id>/<str:dish_name>', add_item_cart, name='add_item_cart'),
    path('remove-item-cart/<str:dish_id>/<str:dish_name>', remove_item_cart, name='remove_item_cart'),

    path('cart/', cart_listing, name='cart_listing'),
    path('place-order/', place_order, name='place_order'),

    path('past-orders/', order_history, name='past_orders'),
    path('analytics/', analytics, name='analytics'),
]

restaurant_app/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MinValueValidator, MaxValueValidator
from accounts.models import CustomUser
from django.dispatch import receiver
from django.db.models.signals import post_save
import uuid
from django.utils import timezone


class RestaurantDetail(models.Model):
    name = models.CharField(max_length=50)
    address = models.TextField(unique=True, validators=[
        MinLengthValidator(limit_value=5, message='Address should be atleast 5 characters long')])
    manager = models.ForeignKey(CustomUser, on_delete=models.CASCADE)


    def __str__(self):
        return self.name


class Dish(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(limit_value=20), MaxValueValidator(limit_value=3000)])
    description = models.TextField(blank=True, null=True)
    restaurant = models.ForeignKey(RestaurantDetail, on_delete=models.CASCADE)
    img_link = models.URLField(null=True, blank=True)
    updation_date = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True)
    
    class Meta:
        verbose_name_plural = 'Dishes'

    def __str__(self):
        return self.name + ' | ' + self.restaurant.name
    


class Cart(models.Model):
    cart_owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    order_placed = models.BooleanField(default=False)

    def __str__(self):
        return self.cart_owner


class OrderDetail(models.Model):
    placed_by = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    dish = models.ForeignKey(Dish, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(validators=[MinValueValidator(limit_value=0), MaxValueValidator(5)], default=1)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    order_placed = models.BooleanField(default=False)
    order_time = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.placed_by.username + ' | ' + self.dish.name + ' | ' + str(self.order_time)
    


############### Signal #################

@receiver(post_save, sender=RestaurantDetail)
def restau_creation(sender, instance, created, **kwargs):
    if created:
        manager_obj = instance.manager
        manager_obj.user_type = 'restaurant_manager'
        manager_obj.save()
        print('user converted to manager')

restaurant_app/forms.py
from django import forms

class DateRangeForm(forms.Form):
    date1 = forms.DateField(label='Start Date ', widget=forms.DateInput(attrs={'type': 'date'}))
    date2 = forms.DateField(label='End Date ', widget=forms.DateInput(attrs={'type': 'date'}))

    def clean(self):
        cleaned_data = super().clean()
        date1 = cleaned_data.get('date1')
        date2 = cleaned_data.get('date2')

        if date1 and date2 and date1 >= date2:
            raise forms.ValidationError("End date should be greater than start date.")

        return cleaned_data

restaurant_app/views.py
from django.views.generic import ListView
import json
from django.shortcuts import render
from .models import Dish, OrderDetail
from django.core.paginator import Paginator
from django.db.models import Q, Sum
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from pprint import pprint
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from restaurant_app.utils import add_item_operation, remove_item_operation, create_order_from_session, get_date_range, get_date_obj
from .forms import DateRangeForm


class DishListing(LoginRequiredMixin, ListView):
    model = Dish
    template_name = 'restaurant_app/dish_listing.html'
    context_object_name = 'dish'
    paginate_by = 5
    
    def get_queryset(self):
        return super().get_queryset().order_by('-updation_date')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_term = self.request.GET.get('search_term')
        if search_term is not None and search_term not in ['', 'none']:
            print('rann----')
            context['search_term'] = search_term
            queryset = self.get_queryset().filter(Q(name__icontains=search_term) | Q(restaurant__name__icontains=search_term))
        else:
            queryset = self.get_queryset()
        
        # pagination logic
        paginator = Paginator(queryset, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj

        # message logic
        if self.request.session.get('dish_operation'):
            messages.success(self.request, self.request.session.get('dish_operation'))
            self.request.session.pop('dish_operation')
            self.request.session.save()

        # item logic
        user_email = self.request.user.email
        if 'cart_session' in self.request.session and user_email in self.request.session['cart_session']:
            context['quantity'] = dict(self.request.session['cart_session'][user_email])
            pprint(context['quantity'], indent=2)
        return context


@login_required(login_url='accounts_app:login')
def add_item(request, page, dish_id, dish_name, search_term='none'):
    add_item_operation(request, dish_id, dish_name)
    # pprint(dict(request.session), indent=2)
    if search_term != 'none':
        url = reverse('restaurant_app:dish_listing') + f'?page={page}&search_term={search_term}'
    else:
        url = reverse('restaurant_app:dish_listing') + f'?page={page}'
    return redirect(url)


@login_required(login_url='accounts_app:login')
def remove_item(request, page, dish_id, dish_name, search_term='none'):
    remove_item_operation(request, dish_id, dish_name)
    # pprint(dict(request.session), indent=2)
    if search_term != 'none':
        url = reverse('restaurant_app:dish_listing') + f'?page={page}&search_term={search_term}'
    else:
        url = reverse('restaurant_app:dish_listing') + f'?page={page}'
    return redirect(url)


@login_required(login_url='accounts_app:login')
def add_item_cart(request, dish_id, dish_name):
    add_item_operation(request, dish_id, dish_name)
    # pprint(dict(request.session), indent=2)
    url = reverse('restaurant_app:cart_listing')
    return redirect(url)


@login_required(login_url='accounts_app:login')
def remove_item_cart(request, dish_id, dish_name):
    remove_item_operation(request, dish_id, dish_name)
    # pprint(dict(request.session), indent=2)
    url = reverse('restaurant_app:cart_listing')
    return redirect(url)


@login_required(login_url='accounts_app:login')
def cart_listing(request):
    session_dishes_dict = {}
    user_email = request.user.email
    cart_session = request.session.get('cart_session')
    if cart_session and user_email in cart_session:
        session_dishes_dict = cart_session[user_email]
    
    matching_dishes = Dish.objects.filter(id__in=session_dishes_dict.keys())
    context = {'cart_dishes': matching_dishes}

    if 'cart_session' in request.session and user_email in request.session['cart_session']:
        context['quantity'] = dict(request.session['cart_session'][user_email])
    
    # message logic
    if request.session.get('dish_operation'):
        messages.success(request, request.session.get('dish_operation'))
        request.session.pop('dish_operation')
    
    return render(request, 'restaurant_app/cart_listing.html', context)


@login_required(login_url='accounts_app:login')
def place_order(request):
    session_dishes_dict = {}
    user_email = request.user.email
    cart_session = request.session.get('cart_session')
    if cart_session and user_email in cart_session:
        session_dishes_dict = cart_session[user_email]
    else:
        print('cart_session or email not available')
        return redirect('restaurant_app:sih_listing')
    
    matching_dishes = Dish.objects.filter(id__in=session_dishes_dict.keys())
    create_order_from_session(matching_dishes, session_dishes_dict, request.user)
    request.session['cart_session'].pop(user_email)
    request.session.save()
    return render(request, 'restaurant_app/order_confirmed.html')
        

class OrderHistory(LoginRequiredMixin, ListView, ):
    model = OrderDetail
    template_name = 'restaurant_app/order_history.html'
    context_object_name = 'ordered_dishes'
    paginate_by = 5

    def get_queryset(self):
        return super().get_queryset().order_by('-order_time')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if self.request.method == 'POST':
            print('R1')
            queryset = self.get_queryset().filter(placed_by=user, order_placed=True)
        else:
            queryset = self.get_queryset().filter(placed_by=user, order_placed=True)
        paginator = Paginator(queryset, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj


        return context


@login_required(login_url='accounts_app:login')
def order_history(request):
    user = request.user
    paginate_by = 5
    context = {}
    if request.GET.get('duration') and request.GET['duration'] != 'All orders':
        duration = request.GET.get('duration')
        context['selected_duration'] = duration
        range1, range2 = get_date_range(duration)
        # print(range1, range2)
        queryset = OrderDetail.objects.filter(placed_by=user, order_placed=True, order_time__range=(range2, range1)).order_by('-order_time')
    else:
        queryset = OrderDetail.objects.filter(placed_by=user, order_placed=True).order_by('-order_time')
    paginator = Paginator(queryset, paginate_by)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context['page_obj'] = page_obj

    return render(request, 'restaurant_app/order_history.html', context)


@login_required(login_url='accounts_app:login')
def analytics(request):
    form = DateRangeForm(request.GET)
    if request.method == "GET" and form.is_valid():
        print('true')
        date1 = (form.cleaned_data['date1'])
        date2 = form.cleaned_data['date2']
        d1 = get_date_obj(date1)
        d2 = get_date_obj(date2)
        orders = OrderDetail.objects.filter(order_time__range=(d1, d2)).values('dish').annotate(total_quantity=Sum('quantity'))
        total_sales = OrderDetail.objects.filter(order_time__range=(d1, d2)).aggregate(total_amount=Sum('quantity'))
        restaurants = OrderDetail.objects.filter(order_time__range=(d1, d2)).values('dish__restaurant__name').annotate(total_quantity=Sum('quantity'))
    else:
        orders = OrderDetail.objects.values('dish').annotate(total_quantity=Sum('quantity'))
        total_sales = OrderDetail.objects.aggregate(total_amount=Sum('quantity'))
        restaurants = OrderDetail.objects.values('dish__restaurant__name').annotate(total_quantity=Sum('quantity'))
    item_list = []
    for order in orders:
        dish = Dish.objects.get(id=str(order['dish']))
        local = {
            "name": dish.name + ' | ' + dish.restaurant.name,
            "quantity": order['total_quantity']
        }
        item_list.append(local)
    context = {'items': json.dumps(item_list)}


    
    restaurants_list = []
    for restau in restaurants:
        local = {
            'name': restau['dish__restaurant__name'],
            'percentage': restau['total_quantity']/total_sales['total_amount']*100
        }
        restaurants_list.append(local)
    context['categories'] = json.dumps(restaurants_list)
    if request.method == "GET" and form.is_valid():
        context['form'] = DateRangeForm(request.GET)
    else:
        context['form'] = DateRangeForm()
    return render(request, 'restaurant_app/analytics.html', context)

templates/restaurant_app/analytics.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %}Analytics{% endblock %}

{% block body_block %}

<div class="row justify-content-center mt-4">
    <div class="col-6">
        <form method="get" action="{% url 'restaurant_app:analytics' %}">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6">
                    {{ form.date1.label_tag }}
                    {{ form.date1 }}
                </div>
                <div class="form-group col-md-6">
                    {{ form.date2.label_tag }}
                    {{ form.date2 }}
                </div>
            </div>
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">Apply</button>
            </div>
        </form>
    </div>
</div>


<div class="text-center mt-3">
    <h2>Restaurant Sales %</h2>
</div>
<div style="width: 80%; margin: auto;">
    <canvas id="doughnutChart"></canvas>
</div>

<div class="text-center mt-5">
    <h2>Dish Sales</h2>
</div>
<div style="width: 80%; margin: auto;">
    <canvas id="myChart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var items = JSON.parse('{{ items | safe }}');

    var labels = items.map(item => item.name);
    var data = items.map(item => item.quantity);

    var chart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: labels,
            datasets: [{
                label: 'Quantity',
                data: data,
                backgroundColor: 'rgba(75, 192, 192, 0.2)',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 1
            }]
        },
        options: {
            indexAxis: 'y',
        }
    });


    var ctx2 = document.getElementById('doughnutChart').getContext('2d');
    var categories = JSON.parse('{{ categories | safe }}');

    var categoryNames = categories.map(category => category.name);
    var percentages = categories.map(category => category.percentage);

    var chart = new Chart(ctx2, {
        type: 'doughnut',
        data: {
            labels: categoryNames,
            datasets: [{
                data: percentages,
                backgroundColor: [
                    'rgba(255, 99, 132, 0.2)',
                    'rgba(54, 162, 235, 0.2)',
                    'rgba(255, 206, 86, 0.2)',
                    'rgba(75, 192, 192, 0.2)',
                    'rgba(153, 102, 255, 0.2)',
                    // Add more colors as needed
                ],
                borderColor: [
                    'rgba(255, 99, 132, 1)',
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 206, 86, 1)',
                    'rgba(75, 192, 192, 1)',
                    'rgba(153, 102, 255, 1)',
                    // Add more colors as needed
                ],
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false
        }
    });


</script>

{% endblock %}

templates/restaurant_app/cart_listing.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %}Cart{% endblock %}

{% block body_block %}


<div class="row mx-2">

    <div class="col-md-2 my-2"></div>

    <div class="col-md-8 my-2">
        <div class="container mt-4">
            <h1>Cart Items</h1>
            {% if cart_dishes %}
            <ul class="list-group mt-4">
                {% for dish in cart_dishes %}
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-md-3">
                            <!-- Column 1: Image of the book -->
                            <img src="{{dish.img_link}}" alt="Dish Image" class="img-fluid" style="height: auto; width: 200px;">
                        </div>
                        <div class="col-md-6">
                                    <h5><strong>{{ dish.name }}</strong></h5>
                                    Price: ₹{{ dish.price }}<br>
                                    <strong>{{ dish.restaurant.name }}</strong><br>
                                    Desc: {{ dish.description }}
                        </div>
                        <div class="col-md-3">
                            <div class="row my-4 mx-auto">
                                <a href="{% url 'restaurant_app:remove_item_cart' dish_id=dish.id dish_name=dish.name %}"><button class="btn btn-secondary col" id="decrement">-</button></a>
                            {% if dish.id|stringformat:"s" in quantity %}
                            <input type="number" id="quantity" class="form-control text-center col" value="{{ dish.id|get_dict_value:quantity }}" readonly>
                            {% else %}
                            <input type="number" id="quantity" class="form-control text-center col" value="0" readonly>
                            {% endif %}
                            <a href="{% url 'restaurant_app:add_item_cart' dish_id=dish.id dish_name=dish.name %}"><button class="btn btn-secondary col" id="increment">+</button></a>
                            </div>
                            <div>Sub Total: ₹<span id="sub-total">{{dish.id|get_dict_value:quantity|multiply:dish.price}}</span></div>
                        </div>
                    </div>
                </li>
                
                {% endfor %}
            </ul>
            {% else %}
            <h3 class="text-center">Your cart is empty. Click <a href="{% url 'restaurant_app:dish_listing' %}">here</a> to see available items.</h3>
            {% endif %}
        </div>


    </div>

    <div class="col-md-2 my-2">
        {% if cart_dishes %}
        <p>Grand Total: ₹<span id="total-value"></span></p>
        <a href="{% url 'restaurant_app:place_order' %}"><button class="btn btn-success">Place Order</button></a>
        {% endif %}
    </div>
</div>

<script>
    // Get all elements with the id 'sub-total'
    const subTotalElements = document.querySelectorAll('[id="sub-total"]');
    
    // Initialize a variable to hold the total value
    let totalValue = 0;
    
    // Loop through each 'sub-total' element and add its value to the total
    subTotalElements.forEach(element => {
        const value = parseFloat(element.innerText); // Convert the inner text to a float
        totalValue += value;
    });
    
    // Update the total value in the HTML
    const totalValueElement = document.getElementById('total-value');
    totalValueElement.textContent = totalValue;
</script>

{% endblock %}

templates/restaurant_app/dish_listing.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %}Dishes{% endblock %}

{% block body_block %}


<div class="row justify-content-center mt-4">
    <div class="col-auto">
        <form class="form-inline" method="GET" action="{% url 'restaurant_app:dish_listing' %}">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="dish / restaurant" aria-label="Search" name="search_term">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="submit">Search</button>
                </div>
            </div>
        </form>
    </div>
</div>


<div class="row mx-2">

    <div class="col-md-2 my-2"></div>

    <div class="col-md-8 my-2">
        <div class="container mt-4">
            <h1>Dishes Available</h1>
            <ul class="list-group mt-4">
                {% for dish in page_obj %}
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-md-3">
                            <!-- Column 1: Image of the book -->
                            <img src="{{dish.img_link}}" alt="Dish Image" class="img-fluid" style="height: auto; width: 200px;">
                        </div>
                        <div class="col-md-6">
                                    <h5><strong>{{ dish.name }}</strong></h5>
                                    Price: ₹{{ dish.price }}<br>
                                    <strong>{{ dish.restaurant.name }}</strong><br>
                                    Desc: {{ dish.description }}
                        </div>

                        <div class="col-md-3">
                                <div class="row my-4 mx-auto">
                                    {% if search_term %}
                                        <a href="{% url 'restaurant_app:remove_item' page=page_obj.number dish_id=dish.id dish_name=dish.name search_term=search_term %}"><button class="btn btn-secondary col" id="decrement">-</button></a>
                                    {% else %}
                                        <a href="{% url 'restaurant_app:remove_item' page=page_obj.number dish_id=dish.id dish_name=dish.name %}"><button class="btn btn-secondary col" id="decrement">-</button></a>
                                    {% endif %}
                                    
                                    {% if dish.id|stringformat:"s" in quantity %}
                                        <input type="number" id="quantity" class="form-control text-center col" value="{{ dish.id|get_dict_value:quantity }}" readonly>
                                    {% else %}
                                        <input type="number" id="quantity" class="form-control text-center col" value="0" readonly>
                                    {% endif %}
                                    
                                    {% if search_term %}
                                        <a href="{% url 'restaurant_app:add_item' page=page_obj.number dish_id=dish.id dish_name=dish.name search_term=search_term %}"><button class="btn btn-secondary col" id="increment">+</button></a>
                                    {% else %}
                                        <a href="{% url 'restaurant_app:add_item' page=page_obj.number dish_id=dish.id dish_name=dish.name %}"><button class="btn btn-secondary col" id="increment">+</button></a>
                                    {% endif %}
                            </div>
                                {% if dish.id|stringformat:"s" in quantity %}
                                <div>Sub Total: ₹{{dish.id|get_dict_value:quantity|multiply:dish.price}}</div>
                                {% endif %}
                        </div>
                    </div>
                </li>
                
                {% endfor %}
            </ul>
        </div>


    </div>

    <div class="col-md-2 my-2">
        <ul>
            <li>Search for dishes and restaurants from search bar</li>
            <li>Click on +/- symbol to add or remove item in cart</li>
            <li>Click on Cart to view/edit and place your order</li>
            <li>Click on Orders to view past orders</li>
          </ul>
    </div>
</div>

<nav aria-label="Page navigation" class="mt-4">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1{% if search_term %}&search_term={{ search_term }}{% endif %}">&laquo; First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if search_term %}&search_term={{ search_term }}{% endif %}">Previous</a>
        </li>
        {% endif %}

        <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>

        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{% if search_term %}&search_term={{ search_term }}{% endif %}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if search_term %}&search_term={{ search_term }}{% endif %}">Last &raquo;</a>
        </li>
        {% endif %}
    </ul>
</nav>


{% endblock %}

templates/restaurant_app/order_confirmed.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %}Order Confirmed{% endblock %}

{% block body_block %}


<div class="row mx-2">

    <div class="col-md-2 my-2"></div>

    <div class="col-md-8 my-2">
        <div class="container mt-4">
            <h1 class="text-center">Order Confirmed</h1>
            <h3 class="text-center">Your order will be delivered soon. Click <a href="{% url 'restaurant_app:dish_listing' %}">here</a> to see available items.</h3>
        </div>
    </div>

    <div class="col-md-2 my-2">
    </div>
</div>

{% endblock %}

templates/restaurant_app/order_history.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %}Order History{% endblock %}

{% block body_block %}



<div class="row mx-2">

    <div class="col-md-2 my-2"></div>

    <div class="col-md-8 my-2">
        <div class="container mt-4">
            <h1>Past Orders</h1>
            <ul class="list-group mt-4">
                {% for dish in page_obj %}
                <li class="list-group-item" id="dish">
                    <div class="row">
                        <div class="col-md-3">
                            <!-- Column 1: Image of the book -->
                            <img src="{{dish.dish.img_link}}" alt="Dish Image" class="img-fluid"
                                style="height: auto; width: 200px;">
                        </div>
                        <div class="col-md-6">
                            <h5><strong>{{ dish.dish.name }}</strong></h5>
                            Quantity: {{ dish.quantity }}<br>
                            Price: ₹{{ dish.total_price }}<br>
                            <strong>{{ dish.dish.restaurant.name }}</strong><br>
                            Order Time: {{ dish.order_time }}
                        </div>
                        <div class="col-md-3">
                        </div>
                    </div>
                </li>

                {% endfor %}
            </ul>
        </div>


    </div>

    <div class="col-md-2 my-2">
        <form method="get" action="{% url 'restaurant_app:past_orders' %}">
            <div class="form-group">
                <label for="exampleFormControlSelect1">Filter on date</label>
                <select class="form-control" id="exampleFormControlSelect1" name="duration">
                    <option value="All orders" >All orders</option>
                    <option value="Past 1 day" {% if selected_duration == 'Past 1 day' %}selected{% endif %}>Past 1 day</option>
                    <option value="Past 3 days" {% if selected_duration == 'Past 3 days' %}selected{% endif %}>Past 3 days</option>
                    <option value="Past week" {% if selected_duration == 'Past week' %}selected{% endif %}>Past week</option>
                    <option value="Past month" {% if selected_duration == 'Past month' %}selected{% endif %}>Past 30 days</option>
                    <option value="Past year" {% if selected_duration == 'Past year' %}selected{% endif %}>Past year</option>
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Apply</button>
        </form>
    </div>
</div>

<nav aria-label="Page navigation" class="mt-4">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1{% if selected_duration %}&duration={{ selected_duration }}{% endif %}">&laquo; First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if selected_duration %}&duration={{ selected_duration }}{% endif %}">Previous</a>
        </li>
        {% endif %}

        <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>

        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{% if selected_duration %}&duration={{ selected_duration }}{% endif %}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if selected_duration %}&duration={{ selected_duration }}{% endif %}">Last &raquo;</a>
        </li>
        {% endif %}
    </ul>
</nav>


{% endblock %}