accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import index, RegisterView, test_restricted_view, CustomLoginView


app_name = 'accounts_app'

urlpatterns = [
    path('index/', index, name='index'),
    path('register/', RegisterView.as_view(), name='register'),
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='accounts_app:login'), name='logout'),
    path('test/restricted-view/', test_restricted_view, name='test_restricted_view')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('restaurant_app.urls')),
]

restaurant_app/urls.py
from django.urls import path
from .views import (DishListing, add_item, remove_item, cart_listing, add_item_cart,
                    remove_item_cart, place_order, OrderHistory, order_history, analytics)

app_name = 'restaurant_app'

urlpatterns = [
    path('home/', DishListing.as_view(), name='dish_listing'),

    path('add-item/<int:page>/<str:dish_id>/<str:dish_name>/', add_item, name='add_item'),
    path('add-item/<int:page>/<str:dish_id>/<str:dish_name>/<str:search_term>', add_item, name='add_item'),

    path('remove-item/<int:page>/<str:dish_id>/<str:dish_name>/', remove_item, name='remove_item'),
    path('remove-item/<int:page>/<str:dish_id>/<str:dish_name>/<str:search_term>', remove_item, name='remove_item'),

    path('add-item-cart/<str:dish_id>/<str:dish_name>', add_item_cart, name='add_item_cart'),
    path('remove-item-cart/<str:dish_id>/<str:dish_name>', remove_item_cart, name='remove_item_cart'),

    path('cart/', cart_listing, name='cart_listing'),
    path('place-order/', place_order, name='place_order'),

    path('past-orders/', order_history, name='past_orders'),
    path('analytics/', analytics, name='analytics'),
]

templates/base.html
{% load static %}
{% load custom_filters %}
{% load d2 %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <div class="sticky-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-warning">
      <img src="{% static 'base/pizza.png' %}" alt="My Image" style="height: 45px; width: auto;">
      <a class="navbar-brand ml-1 text-dark" href="{% url 'restaurant_app:dish_listing' %}"><strong>Somato</strong></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link text-dark" href="{% url 'restaurant_app:cart_listing' %}"> Cart <span
                class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link text-dark" href="{% url 'restaurant_app:past_orders' %}"> Orders <span
                class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link text-dark" href="{% url 'admin:index' %}" target="_blank">Admin Panel <span
              class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link text-dark" href="{% url 'restaurant_app:analytics' %}">Analytics <span
                class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link text-dark" href="{% url 'accounts_app:logout' %}">logout <span
                    class="sr-only">(current)</span></a>
              </li>
          {% else %}
          <li class="nav-item active">
            <a class="nav-link text-dark" href="{% url 'admin:index' %}">Admin Panel <span
                class="sr-only">(current)</span></a>
          </li>
          {% endif %}
        </ul>
        {% if user.is_authenticated %}
        <span class="navbar-text text-dark">
          Hi {{ request.user.full_name }}
        </span>
        {% endif %}
      </div>
    </nav>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>{{message}}</strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endif %}
  </div>

  {% block body_block %}
  {% endblock %}
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script>
    window.onbeforeunload = function () {
      var scrollPosition = window.scrollY || window.pageYOffset;
      sessionStorage.setItem('scrollPosition', scrollPosition);
    };
    document.addEventListener('DOMContentLoaded', function () {
      var scrollPosition = sessionStorage.getItem('scrollPosition');
      if (scrollPosition !== null) {
        window.scrollTo(0, parseInt(scrollPosition));
        sessionStorage.removeItem('scrollPosition');
      }
    });
  </script>

</body>

</html>